<?php

declare(strict_types=1);

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * v4.2/W4 sub-PR 6 — master switch for the Flow Admin cockpit.
 *
 * The vendor `padosoft/laravel-flow-admin` v1.0 always registers its
 * routes when the service provider boots — there is no upstream
 * `enabled` flag. AskMyDocs adds one (`FLOW_ADMIN_ENABLED`, default
 * false) so the admin surface stays dark until an operator opts in.
 *
 * When the env switch is off:
 *   - Every request to a route under the configured prefix returns
 *     a clean 404 (R14 — correct semantic for a disabled subsystem).
 *   - The 404 is generated by Laravel's HttpException flow, so the
 *     response carries no body and no JSON shape that hints the
 *     subsystem exists. From the outside it is indistinguishable
 *     from a route that never existed.
 *
 * Registered as a route middleware alias `flow-admin.enabled` by
 * {@see \App\Providers\FlowAdminIntegrationServiceProvider} so it can
 * be referenced from `config/flow-admin.php::middleware`.
 */
final class FlowAdminEnabled
{
    public function handle(Request $request, Closure $next): Response
    {
        if ((bool) config('flow-admin.enabled', false) !== true) {
            abort(404);
        }

        return $next($request);
    }
}
