<?php

declare(strict_types=1);

namespace App\Notifications\Channels;

use App\Models\User;
use App\Notifications\Events\BaseNotificationEvent;

/**
 * v8.0/W2.1 — generic outbound webhook channel adapter.
 *
 * Posts a flat JSON envelope to an operator-configured URL with an
 * HMAC-SHA256 signature in the `X-AskMyDocs-Signature` header so
 * the receiver can verify the payload was generated by this
 * AskMyDocs instance (and not replayed by a third party). Unlike
 * Discord / Slack / Teams the receiver is unspecified — the channel
 * does NOT shape the payload for any particular consumer; it ships
 * the raw event fields so downstream automations can reformat as
 * needed:
 *
 *   {
 *     "event_type":     "kb_doc_created",   // NotificationEvent::EVENT_* snake_case
 *     "tenant_id":      "default",
 *     "user_id":        42,                 // null for tenant-wide events
 *     "user_email":     "alice@example.com",
 *     "subject":        "New document published in your knowledge base",
 *     "summary":        "A document <slug> was added under <project>",
 *     "payload":        { ...event payload as-is... },
 *     "sent_at":        "2026-05-19T14:30:00+00:00"
 *   }
 *
 * The HMAC signature is `sha256=<hex>` over the JSON-encoded body
 * BYTES (with `JSON_UNESCAPED_SLASHES`) — receivers verify by
 * computing `hmac_sha256(raw_body, shared_secret)` and comparing
 * against the header. The signature shipping in
 * `SendExternalNotificationJob` is the load-bearing path; this
 * channel just supplies the secret via {@see resolveSecret()}.
 *
 * See {@see AbstractWebhookChannel} for the rest of the lifecycle.
 */
final class WebhookChannel extends AbstractWebhookChannel
{
    public function name(): string
    {
        return 'webhook';
    }

    protected function configKey(): string
    {
        return 'askmydocs.notifications.channels.webhook';
    }

    /**
     * @return array<string, mixed>
     */
    protected function buildPayload(BaseNotificationEvent $event, ?User $user): array
    {
        $eventType = $event->eventType();
        $rawPayload = $event->payload();

        return [
            'event_type' => $eventType,
            'tenant_id' => $event->tenantId(),
            'user_id' => $user?->id,
            'user_email' => $user?->email,
            'subject' => NotificationSubjects::forEventType($eventType),
            'summary' => NotificationSummaries::forEventType($eventType, $rawPayload),
            'payload' => $rawPayload,
            'sent_at' => now()->toIso8601String(),
        ];
    }
}
