<?php

declare(strict_types=1);

namespace Tests\Fixtures\Pdf;

/**
 * Pure-PHP minimal PDF builder for test fixtures.
 *
 * Generates a deterministic multi-page PDF byte string that smalot/pdfparser
 * can parse end-to-end. Used by PdfConverterTest + PdfIngestionTest so we
 * don't have to commit binary fixtures (binary blobs in git diff hide
 * regressions in test data).
 *
 * The output complies with the PDF 1.4 minimum viable subset:
 *  - Catalog / Pages tree
 *  - One Page object per text page
 *  - One Content stream per page (BT / Tf / Td / Tj / ET text operators)
 *  - Type1 base font Helvetica (no font embedding required)
 *  - Cross-reference table with byte-accurate offsets
 *  - Trailer + startxref
 *
 * Limitations (intentional — keep the fixture builder small):
 *  - No images, no embedded fonts, no compression streams.
 *  - ASCII text only (no Unicode escapes). Sufficient for assertion text
 *    like "Page 1: Lorem ipsum about A.".
 *
 * If smalot's parser ever rejects this format, switch to a checked-in
 * binary fixture generated by an external tool (wkhtmltopdf, dompdf) and
 * deprecate this builder.
 */
final class PdfFixtureBuilder
{
    /**
     * Build a 3-page PDF with one distinctive line per page. Used by both
     * the unit converter test and the feature ingestion test so assertions
     * can target the same predictable text.
     */
    public static function buildThreePageSample(): string
    {
        return self::build([
            'Page 1: Lorem ipsum about A.',
            'Page 2: Lorem ipsum about B.',
            'Page 3: Lorem ipsum about C.',
        ]);
    }

    /**
     * Build a single-page PDF — useful for the converter's edge-case tests
     * (single-page extraction, page_count == 1).
     */
    public static function buildSinglePage(string $text = 'Single page body.'): string
    {
        return self::build([$text]);
    }

    /**
     * @param  list<string>  $pageTexts  one element = one page (ASCII only).
     *
     * @throws \InvalidArgumentException when `$pageTexts` is empty — a PDF
     *         with zero pages produces an invalid `/Kids []` list and a
     *         malformed Pages object that smalot cannot parse. Callers
     *         must always provide ≥1 page.
     */
    public static function build(array $pageTexts): string
    {
        if ($pageTexts === []) {
            throw new \InvalidArgumentException(
                'PdfFixtureBuilder::build() requires at least one page; got empty array.',
            );
        }

        $objects = [];
        $pageCount = count($pageTexts);

        // Object IDs (sequential):
        //   1 = Catalog
        //   2 = Pages
        //   3..(2+N) = Page objects
        //   (3+N)..(2+2N) = Content streams
        //   (3+2N) = Font

        $catalogId = 1;
        $pagesId = 2;
        $firstPageId = 3;
        $firstContentId = $firstPageId + $pageCount;
        $fontId = $firstContentId + $pageCount;

        $kidsList = implode(' ', array_map(
            fn (int $i) => ($firstPageId + $i) . ' 0 R',
            range(0, $pageCount - 1),
        ));

        $objects[$catalogId] = "<< /Type /Catalog /Pages {$pagesId} 0 R >>";
        $objects[$pagesId] = "<< /Type /Pages /Kids [{$kidsList}] /Count {$pageCount} >>";

        for ($i = 0; $i < $pageCount; $i++) {
            $pageId = $firstPageId + $i;
            $contentId = $firstContentId + $i;
            $objects[$pageId] = "<< /Type /Page /Parent {$pagesId} 0 R /Contents {$contentId} 0 R "
                . "/Resources << /Font << /F1 {$fontId} 0 R >> >> "
                . "/MediaBox [0 0 612 792] >>";

            // Escape PDF string literal: backslash, parens, line breaks. ASCII only here.
            $escaped = self::escapeStringLiteral($pageTexts[$i]);
            $stream = "BT\n/F1 12 Tf\n100 700 Td\n({$escaped}) Tj\nET";
            $objects[$contentId] = "<< /Length " . strlen($stream) . " >>\nstream\n{$stream}\nendstream";
        }

        $objects[$fontId] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";

        return self::serialize($objects, $catalogId);
    }

    /**
     * Serialize the object table into a PDF byte string with a byte-accurate
     * cross-reference table. The xref table holds the absolute byte offset
     * of each `N 0 obj` line — getting this wrong is the #1 reason smalot
     * rejects a hand-crafted PDF, so the offsets are tracked while writing.
     *
     * @param  array<int, string>  $objects  keyed by object ID
     */
    private static function serialize(array $objects, int $catalogId): string
    {
        // PDF header — the 4-byte binary marker on line 2 hints to viewers
        // that this is NOT a 7-bit-clean file (smalot doesn't care, but
        // keeping the marker matches the reference spec).
        $out = "%PDF-1.4\n%\xE2\xE3\xCF\xD3\n";
        $offsets = [];

        ksort($objects);
        foreach ($objects as $id => $body) {
            $offsets[$id] = strlen($out);
            $out .= "{$id} 0 obj\n{$body}\nendobj\n";
        }

        $xrefOffset = strlen($out);
        $maxId = max(array_keys($objects));
        $out .= "xref\n0 " . ($maxId + 1) . "\n";
        $out .= sprintf("%010d %05d f \n", 0, 65535); // free entry for object 0
        for ($i = 1; $i <= $maxId; $i++) {
            $offset = $offsets[$i] ?? 0;
            $out .= sprintf("%010d %05d n \n", $offset, 0);
        }

        $out .= "trailer\n<< /Size " . ($maxId + 1) . " /Root {$catalogId} 0 R >>\n";
        $out .= "startxref\n{$xrefOffset}\n%%EOF\n";

        return $out;
    }

    private static function escapeStringLiteral(string $s): string
    {
        return strtr($s, [
            '\\' => '\\\\',
            '(' => '\\(',
            ')' => '\\)',
            "\n" => '\\n',
            "\r" => '\\r',
        ]);
    }
}
