<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        $isPgsql = DB::getDriverName() === 'pgsql';

        if ($isPgsql) {
            Schema::ensureVectorExtensionExists();
        }

        Schema::create('knowledge_chunks', function (Blueprint $table) use ($isPgsql) {
            $table->id();
            $table->foreignId('knowledge_document_id')->constrained('knowledge_documents')->cascadeOnDelete();
            $table->string('project_key', 120)->index();
            $table->unsignedInteger('chunk_order')->index();
            $table->string('chunk_hash', 64)->index();
            $table->string('heading_path')->nullable()->index();
            $table->text('chunk_text');
            $table->json('metadata')->nullable();
            // Production runs Postgres + pgvector — `vector(1536)` + `vectorIndex()`
            // is the real shape. Non-pgsql connections (SQLite Playwright CI,
            // local MySQL inspection) fall back to a `text` column so the
            // table at least exists; ingestion / retrieval require pgvector
            // and short-circuit elsewhere on those drivers (see
            // KbSearchService + DocumentIngestor for the runtime guards).
            //
            // `nullable()` on both branches: embedding is generated by the
            // IngestDocumentJob and may not exist for a moment between
            // chunk insert and embedding generation. Equally, demo/test
            // seeders that don't have an LLM available need to be able
            // to insert chunk rows without computing real embeddings.
            // The application logic populates embedding before retrieval
            // ever sees the row, so the schema-level nullable doesn't
            // change the user-visible contract.
            if ($isPgsql) {
                $table->vector('embedding', dimensions: 1536)->nullable()->vectorIndex();
            } else {
                $table->text('embedding')->nullable();
            }
            $table->timestamps();

            $table->unique(['knowledge_document_id', 'chunk_hash'], 'uq_kb_chunk_doc_hash');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('knowledge_chunks');
    }
};
