<?php

declare(strict_types=1);

namespace App\Services\Kb\Investigation;

use App\Services\Kb\Retrieval\SearchResult;

/** The only retrieval evidence that may reach an answer prompt. */
final readonly class KbInvestigationResult
{
    /**
     * @param list<array<string, mixed>> $selectedSources
     * @param list<string> $queries
     * @param array{supported_facts:list<string>,missing_facts:list<string>} $factMap
     */
    public function __construct(
        public string $status,
        public string $stopReason,
        public SearchResult $search,
        public array $selectedSources = [],
        public array $queries = [],
        public ?KbInvestigationIntent $intent = null,
        public array $factMap = ['supported_facts' => [], 'missing_facts' => []],
        public array $researchFlows = [],
        public array $attempts = [],
    ) {
    }

    public function isReady(): bool
    {
        return $this->status === 'ready';
    }

    /**
     * Trusted instructions generated by the investigation, not source text.
     * They make a partial response name the material facts the KB did not
     * establish instead of silently filling the gap from model knowledge.
     *
     * @return array{objective:?string,required_facts:list<string>,supported_facts:list<string>,missing_facts:list<string>,partial:bool,language:?string}
     */
    public function answerPromptContext(): array
    {
        return [
            'objective' => $this->intent?->objective,
            'required_facts' => $this->intent?->requiredFacts ?? [],
            'supported_facts' => $this->factMap['supported_facts'] ?? [],
            'missing_facts' => $this->factMap['missing_facts'] ?? [],
            'partial' => $this->stopReason !== 'sufficient_evidence',
            'language' => $this->intent?->understanding?->language,
            'research_flows' => $this->researchFlows,
        ];
    }

    /** @return array{queries:list<string>,stop_reason:string,selected_documents:int,supported_facts:list<string>,missing_facts:list<string>,language:?string} */
    public function trace(): array
    {
        return [
            'status' => $this->status,
            'queries' => $this->queries,
            'stop_reason' => $this->stopReason,
            'selected_documents' => count($this->selectedSources),
            'supported_facts' => $this->factMap['supported_facts'] ?? [],
            'missing_facts' => $this->factMap['missing_facts'] ?? [],
            'language' => $this->intent?->understanding?->language,
            'research_flows' => $this->researchFlows,
            'attempts' => $this->attempts,
        ];
    }
}
