<?php

declare(strict_types=1);

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Queue\SerializesModels;

/**
 * v8.0/W1.3 — queued Mailable carrying a notification body and the
 * one-click unsubscribe link generated by `EmailChannel`.
 *
 * The payload is intentionally flat (scalars only) so the queued
 * job serialisation cost stays bounded — embedding the full
 * `BaseNotificationEvent` would also pull in the recipient User
 * collection on every queue payload.
 */
final class NotificationMail extends Mailable implements ShouldQueue
{
    use Queueable;
    use SerializesModels;

    /**
     * @param  array<string, mixed>  $payload
     */
    public function __construct(
        public readonly string $tenantId,
        public readonly string $eventType,
        public readonly array $payload,
        public readonly int $eventRowId,
        public readonly string $unsubscribeUrl,
        public readonly ?string $userName,
    ) {
    }

    public function envelope(): Envelope
    {
        return new Envelope(
            subject: $this->renderSubject(),
            // R30/R31 tagging — the queue worker sees the tenant on
            // failure log lines without re-loading the event row.
            tags: ['tenant:'.$this->tenantId, 'event:'.$this->eventType],
        );
    }

    public function content(): Content
    {
        return new Content(
            view: 'emails.notification',
            with: [
                'eventType' => $this->eventType,
                'payload' => $this->payload,
                'unsubscribeUrl' => $this->unsubscribeUrl,
                'userName' => $this->userName,
            ],
        );
    }

    /**
     * Human-readable subject line keyed off `event_type`. Templates
     * deliberately kept short (one line) for the v8.0 baseline; the
     * Blade view renders the long-form body with payload details.
     *
     * Match arms use the actual `NotificationEvent::EVENT_*` constants
     * (snake_case, no dots) — not stylised hierarchical strings —
     * because the dispatcher writes `notification_events.event_type`
     * from exactly those constants. Drifting to dot-notation here
     * would silently fall through to the `default` arm for every
     * shipped event type.
     */
    private function renderSubject(): string
    {
        return match ($this->eventType) {
            \App\Models\NotificationEvent::EVENT_KB_DOC_CREATED => 'New document published in your knowledge base',
            \App\Models\NotificationEvent::EVENT_KB_DOC_MODIFIED => 'A document you follow was updated',
            \App\Models\NotificationEvent::EVENT_KB_CANONICAL_PROMOTED => 'A decision was promoted to canonical',
            \App\Models\NotificationEvent::EVENT_KB_DECISION_DEBT_THRESHOLD => 'Decision debt threshold reached',
            \App\Models\NotificationEvent::EVENT_COLLECTION_NEW_MEMBER => 'A new document joined a collection you follow',
            default => 'AskMyDocs notification',
        };
    }
}
